config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'
  after_create :update_post_comments_counter
  after_destroy :decrement_post_comment_counter

  # validates :text, presence: true
  # validates :user_id, presence: true

  def update_post_comments_counter
    post.update(comments_counter: post.comments.count)
  end

  def decrement_post_comment_counter
    post.decrement!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, foreign_key: 'post_id'
  after_create :update_post_likes_counter

  def update_post_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'post_id'
  has_many :likes, foreign_key: 'post_id'

  after_create :update_user_posts_counter
  after_destroy :decrement_user_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true

  validates :likes_counter,
            numericality: {
              only_integer: true,
              greater_than_or_equal_to: 0,
              message: 'must be an integer greater than or equal to zero'
            }, allow_nil: true
  # on: :create
  validates :comments_counter,
            numericality: {
              only_integer: true,
              greater_than_or_equal_to: 0,
              message: 'must be an integer greater than or equal to zero'
            }, allow_nil: true
  # on: :create

  def five_recent_comments
    comments.includes(:user).order(created_at: :desc).limit(5)
  end

  private

  def update_user_posts_counter
    author.increment!(:posts_counter)
  end

  def decrement_user_posts_counter
    author.decrement!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'user_id'
  has_many :comments, foreign_key: 'user_id'
  has_many :likes, foreign_key: 'user_id'

  validates :name, presence: true
  validates :posts_counter,
            numericality: {
              only_integer: true,
              greater_than_or_equal_to: 0,
              message: 'must be an integer greater than or equal to zero'
            },
            on: :create

  def recent_posts(limit = 3)
    posts.order(created_at: :desc).limit(limit)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name email password current_password])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # def new
  #   @comment = Comment.new
  #   @post = Post.find_by(id: params[:post_id])
  #   render :new
  # end
  def new
    @comment = Comment.new
    @post = Post.find_by(id: params[:post_id])
    render :new, locals: { comment: @comment, post: @post }
  end

  def create
    @user = @current_user
    @post = Post.find_by(id: params[:post_id])
    @comment = Comment.includes(:author).new(user_id: @user.id, post_id: @post.id, text: params[:comment][:text])
    if @comment.save
      redirect_to user_post_path(@user, @post), notice: 'Comment was successfully created.'
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = params[:post_id]
    @user = @current_user
    @like = Like.new(author: @user, post_id: @post)
    if @like.save
      flash[:success] = 'You liked this post'
    else
      flash[:alert] = 'You cannot like this post'
    end

    redirect_to user_post_path(@user.id, @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @users = User.find(params[:user_id])
    @posts = @users.posts
    @comments = Comment.where(post_id: @posts.pluck(:id))
    @comments = Comment.all
  end

  def show
    @post = Post.find(params[:id])
    @users = @post.author
    @index = @users.posts.order(created_at: :asc).pluck(:id).index(@post.id)
    @comment = Comment.where(post_id: params[:id])
  end

  def new
    @user = @current_user
    @post = Post.new
    render :new
  end

  def create
    @user = @current_user
    @post = Post.new(post_params)
    @post.user_id = @user.id

    if @post.save
      flash[:success] = 'Post successfully created'
      redirect_to user_posts_url(@post.user_id)
    else
      flash[:alert] = 'Post could not be created'
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text).merge(user_id: @user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with model: [@current_user, @post, Comment.new], url: user_post_comments_path(@current_user, @post), class: 'comment_form' do |form| %>
    <div class="form-group">
      <%= form.text_area :text, class: 'form-control comment_input', placeholder: 'Enter your comment' %>
      <% form.object.errors.full_messages_for(:text).each do |message| %>
        <div class="error-message"><%= message %></div>
      <% end %>
    </div>
    <br>
    <%= form.submit 'Post Comment', class: 'btn btn-primary post_button' %>
  <% end %>

app/views/comments/new.html.erb
<h3> Add new comment</h3>
<div class="comment_container">
  <%= form_with model: @comment, url: user_post_comments_path(@post) do |form| %>
    <div class="comment-form">
      <%= form.text_field :text, required: true, autofocus: true, placeholder: ' Enter your comment here', class: "comment_box" %>
      <%= form.submit "Comment", class: "comment_btn" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="container">
<div class="user-container">

<div class="user-image-cont">
<img src="<%= @users.photo %>" class="user-image">
</div>

<div class="user-info">
<h2><%=link_to @users.name, "/users" %></h2>
  <p>Number of posts: <%= @users.posts.count %></p>
</div>

</div>

<% @posts.each_with_index do |post, index| %>
    <div class="posts <%= 'hidden' if index >= 3 %>">
      <b>Post:<%= index + 1 %> <%= @users.name %></b>
      <p class="post-text">
      <p class="post-text">
<%=link_to post.text, "/users/#{params[:user_id]}/posts/#{post.id}"%>
</p>

      </p>
      <div class="coutner-cont">
      <h6>Comments: <%= post.comments.count %></h6>
      <h6>Likes: <%= post.likes.count %></h6>
      </div>

            <% post.five_recent_comments.each do |comment| %>
                <p><%= comment.user.name %>: <%= comment.text %></p>
            <% end %>

    </div>
  <% end %>

<button class="pagination">Pagination<button>
<a href="/users/<%= @current_user.id %>/posts/new" class="btn btn-primary">New Post</a>
</div>

</div>

app/views/posts/new.html.erb
<h2>Add new post</h2>
<%= form_with model: @post, url: user_posts_path(@user) do |f| %>
  <div class="form-container">
  <label for="post_title">title:</label>
    <%= f.text_field :title, required: true, autofocus: true, class: "form-input", placeholder: "Enter post the title" %>
    <label for="post_title">text:</label>
    <%= f.text_area :text, required: true, autofocus: true, class: "form-input", placeholder: "Enter post the body"%>
    <%= f.submit "Create", class: "create-btn" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="container">

    <div class="posts">

<div class="top-info">
      <b>Post: <%= @index %> <%=link_to @users.name, "/users" %></b>

      <div class="coutner-cont-posts">
      <h6>Comments: <%= @post.comments.count %></h6>
      <h6>Likes: <%= @post.likes.count %></h6>
      </div>
</div>
<p class="post-text">
<%= @post.text %>
</p>
            <% @post.comments.each do |comment| %>
  <p><%= comment.user.name %>: <%= comment.text %></p>
<% end %>
</div>

<div class="comment-like-btn">
      <%= form_with model: @like, url: user_post_likes_path(1, @post), scope: :like do |form|%>
        <%= form.submit 'Like', class: 'btn_1' %>
      <% end %>
      <button type="button" class="btn_2">
        <%= link_to "Comment", new_user_post_comment_path( post_id: @post.id), { class: "user_link" } %>
      </button>
    </div>
</div>

app/views/users/index.html.erb
<div id="user-display">

  <% @users.includes(:comments).each do |user| %>
    <a href="/users/<%= user.id %>" class="user-link">
      <div class="image-user">
        <div class="post-img">
        </div>
        <div class="post">
          <h2><%= user.name %></h2>
          <p>Number of posts: <%= user.posts_counter %></p>
        </div>
      </div>
    </a>
  <% end %>
</div>

app/views/users/show.html.erb
<div id="user-details">
  <div class="user-description">
    <div class="img-div">
      <%= image_tag(@user.photo, class: "img") %>
    </div>
    <div class="user-name">
      <h2><%= @user.name %></h2>
      <p>Number of posts: <%= @user.posts_counter %></p>
    </div>
  </div>
  <div class="bio-description">
    <h3>Bio</h3>
    <p><%= @user.bio%></p>
  </div>

  <% @user.recent_posts.each do |post| %>
    <div class="user-posts">
      <h3><%= link_to post.title, user_post_path(post) %></h3>
      <div><%= post.text %></div>
      <div class="comment-like">
      <span class="comment">Comments: <%= post.comments_counter %></span> <span class="like"span>Likes: <%= post.likes_counter %></span>
    </div>
  </div>
  <% end %>
  <div class="see-posts">
  <a href="/users/<%= @user.id %>/posts" id="user-btn">See all posts</a>
</div>